// Pins the shape of the Bank of Israel rate table and the two lookups the fee depends on.
//
// The table is generated by tools/fetch-boi-rates.mjs from the Bank's own .xls. What
// matters here is not the figures — those come from the source — but that the screen picks
// the right column and the right row, because both choices are silent and both move money.
//
// The column is chosen by the period the rate is committed for, and it differs between the
// two rates the order asks for: the current rate is bucketed by how far the fee is
// discounted (to the next reset on a variable tranche, not to the end of the loan), while
// the origination rate is bucketed by the period the borrower's rate was fixed for.
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../mortgage.html', import.meta.url), 'utf8');
const table = JSON.parse(readFileSync(new URL('../data/boi-mortgage-rates.json', import.meta.url), 'utf8'));

const grab = (a, b) => {
  const s = html.indexOf(a), e = html.indexOf(b, s);
  if (s < 0 || e < 0) throw new Error(`marker not found: ${a}`);
  return html.slice(s, e);
};
// boiBucket and boiRowOn read a module-level `boiRates`; the harness supplies it.
const api = new Function('injected', `
  const isValidYM = ym => typeof ym === 'string' && /^\d{4}-(0[1-9]|1[0-2])$/.test(ym);
  ${grab('function boiBucket(years)', 'const boiLatest')}
  let boiRates = injected;
  return { boiBucket, boiRowOn };
`)(table);
const { boiBucket, boiRowOn } = api;

let failures = 0;
const ok = (cond, name, got = '') => {
  console.log(`${cond ? 'PASS' : 'FAIL'}  ${name}${cond ? '' : `  got: ${got}`}`);
  if (!cond) failures++;
};

// --- the file itself ---
ok(table.rows.length > 100, 'the table carries the full monthly history', String(table.rows.length));
ok(table.buckets.length === 7, 'seven published periods', String(table.buckets.length));
ok(table.rows.every(r => /^\d{4}-\d{2}-\d{2}$/.test(r.from)), 'every row is dated');
ok(table.rows.every((r, i, a) => i === 0 || a[i - 1].from > r.from), 'rows run newest first');
ok(table.rows.every(r => table.buckets.every(b => Number.isFinite(r.rates[b.key]))),
   'every row carries every period');
ok(table.rows.every(r => table.buckets.every(b => r.rates[b.key] > 0 && r.rates[b.key] < 25)),
   'every rate is a plausible percentage');

// --- the column ---
// The Bank's note says each band includes its upper bound, so five years exactly is still
// "over 1 up to 5" and not the next band up.
ok(boiBucket(5) === 'y1to5', 'five years lands in the 1-to-5 band', boiBucket(5));
ok(boiBucket(5.01) === 'y5to10', 'just past five moves up a band', boiBucket(5.01));
ok(boiBucket(1) === 'upTo1', 'one year exactly is the shortest band', boiBucket(1));
ok(boiBucket(25) === 'y20to25', 'twenty-five exactly is still the 20-to-25 band', boiBucket(25));
ok(boiBucket(27.9) === 'over25', 'a 335-month remainder is the over-25 band', boiBucket(27.9));
ok(boiBucket(34 / 12) === 'y1to5', 'a 34-month horizon to a reset is the 1-to-5 band', boiBucket(34 / 12));
ok(boiBucket(0) === null && boiBucket(-3) === null, 'no band for a non-positive period');

// --- the row ---
// The rate in force on a date is the newest publication dated on or before it. Picking the
// following publication instead is the failure that silently understates an older loan.
const newest = table.rows[0], oldest = table.rows[table.rows.length - 1];
ok(boiRowOn(newest.from).from === newest.from, 'a publication date resolves to itself');
ok(boiRowOn('2099-01-01').from === newest.from, 'a future date resolves to the newest row');
ok(boiRowOn('1990-01-01') === null, 'a date before the series starts resolves to nothing');
const mid = table.rows[Math.floor(table.rows.length / 2)];
const dayBefore = new Date(Date.parse(mid.from) - 86400000).toISOString().slice(0, 10);
ok(boiRowOn(dayBefore).from < mid.from, 'the day before a publication still uses the previous one',
   boiRowOn(dayBefore).from);
void oldest;

// --- the date reading, which is where the generator actually broke ---
// LibreOffice writes dates in the locale it happens to be running under. The first run of
// this on a GitHub runner exported 08/13/2026 where this machine exports 13/08/2026, and
// the generator read the American form as day-first: a newest publication of "2026-21-04"
// and the whole table resorted around it. The order is now inferred from the column, so
// both readings have to come out right here.
const tool = readFileSync(new URL('../tools/fetch-boi-rates.mjs', import.meta.url), 'utf8');
const dates = new Function(
  tool.slice(tool.indexOf('const DATE_RE'), tool.indexOf('function parse(csvPath)')) +
  '\n; return { dateOrder, toISO };')();

const dmy = ['13/08/2026', '12/07/2026', '17/06/2024'];
const mdy = ['08/13/2026', '07/12/2026', '06/17/2024'];
ok(dates.dateOrder(dmy) === 'dmy', 'a day above twelve marks the European form', dates.dateOrder(dmy));
ok(dates.dateOrder(mdy) === 'mdy', 'and in second place it marks the American one', dates.dateOrder(mdy));
ok(dates.dateOrder(['2026-08-13']) === 'ymd', 'an ISO export is recognised as itself');
ok(dates.toISO('13/08/2026', 'dmy') === '2026-08-13', 'the European form reads correctly');
ok(dates.toISO('08/13/2026', 'mdy') === '2026-08-13', 'and so does the American one');
// The bug in one line: read the American form as European and you get a thirteenth month.
ok(dates.toISO('08/13/2026', 'dmy') === null, 'a nonexistent month is rejected, not emitted');

// Ambiguity has to be an error rather than a coin flip — silently guessing wrong reorders
// every row and picks the wrong rate for every loan.
let threw = false;
try { dates.dateOrder(['01/02/2026', '03/04/2026']); } catch { threw = true; }
ok(threw, 'a column with nothing above twelve refuses to guess');
threw = false;
try { dates.dateOrder(['13/08/2026', '08/13/2026']); } catch { threw = true; }
ok(threw, 'a column that reads both ways refuses too');

// --- and the generated file must survive the trip ---
ok(table.rows.every(r => !Number.isNaN(Date.parse(r.from))), 'every date in the file is a real one');
ok(table.rows[0].from <= new Date().toISOString().slice(0, 10),
   'the newest publication is not in the future', table.rows[0].from);

process.exit(failures ? 1 : 0);
