// Pins the shape of the Bank of Israel rate table and the two lookups the fee depends on.
//
// The table is generated by tools/fetch-boi-rates.mjs from the Bank's own .xls. What
// matters here is not the figures — those come from the source — but that the screen picks
// the right column and the right row, because both choices are silent and both move money.
//
// The column is chosen by the period the rate is committed for, and it differs between the
// two rates the order asks for: the current rate is bucketed by how far the fee is
// discounted (to the next reset on a variable tranche, not to the end of the loan), while
// the origination rate is bucketed by the period the borrower's rate was fixed for.
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../mortgage.html', import.meta.url), 'utf8');
const table = JSON.parse(readFileSync(new URL('../data/boi-mortgage-rates.json', import.meta.url), 'utf8'));

const grab = (a, b) => {
  const s = html.indexOf(a), e = html.indexOf(b, s);
  if (s < 0 || e < 0) throw new Error(`marker not found: ${a}`);
  return html.slice(s, e);
};
// boiBucket and boiRowOn read a module-level `boiRates`; the harness supplies it.
const api = new Function('injected', `
  const isValidYM = ym => typeof ym === 'string' && /^\d{4}-(0[1-9]|1[0-2])$/.test(ym);
  ${grab('function boiBucket(years)', 'const boiLatest')}
  let boiRates = injected;
  return { boiBucket, boiRowOn };
`)(table);
const { boiBucket, boiRowOn } = api;

let failures = 0;
const ok = (cond, name, got = '') => {
  console.log(`${cond ? 'PASS' : 'FAIL'}  ${name}${cond ? '' : `  got: ${got}`}`);
  if (!cond) failures++;
};

// --- the file itself ---
ok(table.rows.length > 100, 'the table carries the full monthly history', String(table.rows.length));
ok(table.buckets.length === 7, 'seven published periods', String(table.buckets.length));
ok(table.rows.every(r => /^\d{4}-\d{2}-\d{2}$/.test(r.from)), 'every row is dated');
ok(table.rows.every((r, i, a) => i === 0 || a[i - 1].from > r.from), 'rows run newest first');
ok(table.rows.every(r => table.buckets.every(b => Number.isFinite(r.rates[b.key]))),
   'every row carries every period');
ok(table.rows.every(r => table.buckets.every(b => r.rates[b.key] > 0 && r.rates[b.key] < 25)),
   'every rate is a plausible percentage');

// --- the column ---
// The Bank's note says each band includes its upper bound, so five years exactly is still
// "over 1 up to 5" and not the next band up.
ok(boiBucket(5) === 'y1to5', 'five years lands in the 1-to-5 band', boiBucket(5));
ok(boiBucket(5.01) === 'y5to10', 'just past five moves up a band', boiBucket(5.01));
ok(boiBucket(1) === 'upTo1', 'one year exactly is the shortest band', boiBucket(1));
ok(boiBucket(25) === 'y20to25', 'twenty-five exactly is still the 20-to-25 band', boiBucket(25));
ok(boiBucket(27.9) === 'over25', 'a 335-month remainder is the over-25 band', boiBucket(27.9));
ok(boiBucket(34 / 12) === 'y1to5', 'a 34-month horizon to a reset is the 1-to-5 band', boiBucket(34 / 12));
ok(boiBucket(0) === null && boiBucket(-3) === null, 'no band for a non-positive period');

// --- the row ---
// The rate in force on a date is the newest publication dated on or before it. Picking the
// following publication instead is the failure that silently understates an older loan.
const newest = table.rows[0], oldest = table.rows[table.rows.length - 1];
ok(boiRowOn(newest.from).from === newest.from, 'a publication date resolves to itself');
ok(boiRowOn('2099-01-01').from === newest.from, 'a future date resolves to the newest row');
ok(boiRowOn('1990-01-01') === null, 'a date before the series starts resolves to nothing');
const mid = table.rows[Math.floor(table.rows.length / 2)];
const dayBefore = new Date(Date.parse(mid.from) - 86400000).toISOString().slice(0, 10);
ok(boiRowOn(dayBefore).from < mid.from, 'the day before a publication still uses the previous one',
   boiRowOn(dayBefore).from);
void oldest;

// --- reading the workbook, which is where the generator actually broke ---
// The .xls used to be converted through LibreOffice, and that meant reading back what a
// spreadsheet chose to display: dates in the machine's locale, which came out day-first
// here and month-first on a runner and produced a publication dated "2026-21-04". The file
// is now read directly, so a date is a stored serial and cannot be reinterpreted.
const { serialToISO } = await import('../tools/lib/xls-cells.mjs');
ok(serialToISO(46247) === '2026-08-13', 'a serial resolves to its date', serialToISO(46247));
ok(serialToISO(45460) === '2024-06-17', 'and so does one from the origination window', serialToISO(45460));
// The spreadsheet epoch counts a 29th of February 1900 that never happened. Using an
// origin of 1899-12-30 absorbs it from serial 61 onward, which is every date after that
// phantom day and therefore every date this file will ever hold — the series begins in
// 2013, around serial 41000. Below 61 the origin is off by one, deliberately untreated.
ok(serialToISO(61) === '1900-03-01', 'the first of March 1900, just past the phantom day',
   serialToISO(61));
ok(serialToISO(41000) === '2012-04-01', 'a serial from before the series starts', serialToISO(41000));
ok(serialToISO(0) === null && serialToISO(-5) === null && serialToISO(NaN) === null,
   'nothing that is not a date resolves to one');
ok(serialToISO(46247, true) !== serialToISO(46247, false), 'the 1904 epoch is a different date');

// --- and the generated file must survive the trip ---
ok(table.rows.every(r => !Number.isNaN(Date.parse(r.from))), 'every date in the file is a real one');
ok(table.rows[0].from <= new Date().toISOString().slice(0, 10),
   'the newest publication is not in the future', table.rows[0].from);

process.exit(failures ? 1 : 0);
