/**
 * Builds the repo's two generated assets.
 *
 * The app has no build step and deploys straight from main to GitHub Pages, so
 * both outputs are committed. Each carries a header naming its source and that
 * source's sha256; `--check` recomputes the hashes and fails if an output is
 * stale. tools/hooks/pre-commit runs that check so a forgotten rebuild cannot
 * reach production.
 *
 *   node tools/build-assets.mjs           # build
 *   node tools/build-assets.mjs --check   # verify freshness, exit 1 if stale
 *
 * Never touches the repo-root package.json / vite.config.js / package-lock.json —
 * those are local dev setup and are not part of the deployable app.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transformAsync } from '@babel/core';
// Imported as a value, not named as a string: Babel resolves string preset names
// relative to the file being compiled (the repo root), where tools/node_modules
// is not visible.
import presetReact from '@babel/preset-react';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

// Line endings belong to the checkout, not to the source. Git hands Windows
// CRLF and Linux LF for the same commit, so hashing the raw bytes made the
// freshness stamp disagree across machines: a build on either platform
// re-stamped the output, and CI could never agree with a stamp written on
// Windows. Normalising first makes the hash describe content, not platform.
const sha = s => createHash('sha256').update(String(s).replace(/\r\n/g, '\n')).digest('hex').slice(0, 16);
const read = p => readFileSync(join(ROOT, p), 'utf8');

function header(sourceName, hash) {
  return `/* GENERATED from ${sourceName} — source sha256:${hash}\n` +
         ` * Do not edit this file. Edit the source, then run:  node tools/build-assets.mjs\n` +
         ` */\n`;
}

function currentHash(outPath) {
  if (!existsSync(join(ROOT, outPath))) return null;
  const m = read(outPath).match(/source sha256:([0-9a-f]+)/);
  return m ? m[1] : null;
}

const targets = [];

// ---------------------------------------------------------------------------
// 1. tax-optimizer.src.jsx -> tax-optimizer.app.js
//
// Classic runtime, NOT automatic: the source uses the React / ReactDOM UMD
// globals loaded by <script> tags. The automatic runtime would emit an import
// from "react/jsx-runtime" and nothing would run.
// ---------------------------------------------------------------------------
targets.push({
  name: 'tax-optimizer',
  source: 'tax-optimizer.src.jsx',
  out: 'tax-optimizer.app.js',
  async build(src) {
    const { code } = await transformAsync(src, {
      filename: 'tax-optimizer.src.jsx',
      babelrc: false,
      configFile: false,
      compact: false,
      presets: [[presetReact, { runtime: 'classic', pragma: 'React.createElement' }]]
    });
    return code;
  }
});

// ---------------------------------------------------------------------------
// 2. finance.html -> finance.tailwind.css
//
// Replaces cdn.tailwindcss.com, which is the Play CDN: it ships a compiler to
// the browser and regenerates the stylesheet by scanning the DOM on every load —
// on a 648KB document. Tailwind's own docs say it is not for production.
//
// Scanning finance.html alone is enough: nothing else on the page carries
// Tailwind classes (shared/nav.js, sync-widget.js and ai-assistant.js inject
// markup at runtime but style it inline), and there are no interpolated class
// names like `bg-${x}` — every utility appears as a literal the scanner sees.
// ---------------------------------------------------------------------------
targets.push({
  name: 'finance-tailwind',
  source: 'finance.html',
  out: 'finance.tailwind.css',
  async build() {
    const postcss = (await import('postcss')).default;
    const tailwindcss = (await import('tailwindcss')).default;
    const cssnano = (await import('cssnano')).default;

    const result = await postcss([
      tailwindcss({
        content: [join(ROOT, 'finance.html')],
        // Toggled by classList rather than written as a literal in some places.
        // They are literals elsewhere so the scanner already finds them; this
        // costs nothing and removes a whole class of silent breakage.
        safelist: ['hidden', 'tab-active', 'bg-blue-100', 'text-blue-700', 'text-gray-600']
        // preflight stays ON: the Play CDN ships it, so turning it off here would
        // change how the page looks. The goal is byte-for-byte the same rendering,
        // not a tidier stylesheet.
      }),
      cssnano({ preset: 'default' })
    ]).process('@tailwind base;@tailwind components;@tailwind utilities;', { from: undefined });

    return result.css;
  }
});

let stale = 0;
for (const t of targets) {
  const src = read(t.source);
  const hash = sha(src);
  const existing = currentHash(t.out);

  if (check) {
    if (existing !== hash) {
      console.error(`✗ ${t.out} is stale (source ${t.source} changed)`);
      stale++;
    } else {
      console.log(`✓ ${t.out} up to date`);
    }
    continue;
  }

  const code = await t.build(src);
  writeFileSync(join(ROOT, t.out), header(t.source, hash) + code);
  console.log(`✓ built ${t.out} from ${t.source} (${code.split('\n').length} lines)`);
}

if (check && stale) {
  console.error(`\n${stale} generated file(s) stale. Run:  node tools/build-assets.mjs`);
  process.exit(1);
}
