/**
 * Builds the repo's two generated assets.
 *
 * The app has no build step and deploys straight from main to GitHub Pages, so
 * both outputs are committed. Each carries a header naming its source and that
 * source's sha256; `--check` recomputes the hashes and fails if an output is
 * stale. tools/hooks/pre-commit runs that check so a forgotten rebuild cannot
 * reach production.
 *
 *   node tools/build-assets.mjs           # build
 *   node tools/build-assets.mjs --check   # verify freshness, exit 1 if stale
 *
 * Never touches the repo-root package.json / vite.config.js / package-lock.json —
 * those are local dev setup and are not part of the deployable app.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transformAsync } from '@babel/core';
// Imported as a value, not named as a string: Babel resolves string preset names
// relative to the file being compiled (the repo root), where tools/node_modules
// is not visible.
import presetReact from '@babel/preset-react';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

const sha = s => createHash('sha256').update(s).digest('hex').slice(0, 16);
const read = p => readFileSync(join(ROOT, p), 'utf8');

function header(sourceName, hash) {
  return `/* GENERATED from ${sourceName} — source sha256:${hash}\n` +
         ` * Do not edit this file. Edit the source, then run:  node tools/build-assets.mjs\n` +
         ` */\n`;
}

function currentHash(outPath) {
  if (!existsSync(join(ROOT, outPath))) return null;
  const m = read(outPath).match(/source sha256:([0-9a-f]+)/);
  return m ? m[1] : null;
}

const targets = [];

// ---------------------------------------------------------------------------
// 1. tax-optimizer.src.jsx -> tax-optimizer.app.js
//
// Classic runtime, NOT automatic: the source uses the React / ReactDOM UMD
// globals loaded by <script> tags. The automatic runtime would emit an import
// from "react/jsx-runtime" and nothing would run.
// ---------------------------------------------------------------------------
targets.push({
  name: 'tax-optimizer',
  source: 'tax-optimizer.src.jsx',
  out: 'tax-optimizer.app.js',
  async build(src) {
    const { code } = await transformAsync(src, {
      filename: 'tax-optimizer.src.jsx',
      babelrc: false,
      configFile: false,
      compact: false,
      presets: [[presetReact, { runtime: 'classic', pragma: 'React.createElement' }]]
    });
    return code;
  }
});

// ---------------------------------------------------------------------------
// 2. finance.html -> finance.tailwind.css   (added in batch 5)
// ---------------------------------------------------------------------------
// placeholder — registered when the Tailwind batch lands

let stale = 0;
for (const t of targets) {
  const src = read(t.source);
  const hash = sha(src);
  const existing = currentHash(t.out);

  if (check) {
    if (existing !== hash) {
      console.error(`✗ ${t.out} is stale (source ${t.source} changed)`);
      stale++;
    } else {
      console.log(`✓ ${t.out} up to date`);
    }
    continue;
  }

  const code = await t.build(src);
  writeFileSync(join(ROOT, t.out), header(t.source, hash) + code);
  console.log(`✓ built ${t.out} from ${t.source} (${code.split('\n').length} lines)`);
}

if (check && stale) {
  console.error(`\n${stale} generated file(s) stale. Run:  node tools/build-assets.mjs`);
  process.exit(1);
}
